; ability ids
	const_def
	const NO_ABILITY	; 00
	const CHLOROPHYLL	; 01
	const SOLAR_POWER	; 02
	const RAIN_DISH		; 03
	const SHIELD_DUST	; 04
	const SHED_SKIN		; 05
	const COMPOUND_EYES	; 06
	const SNIPER		; 07
	const KEEN_EYE		; 08
	const RUN_AWAY		; 09
	const INTIMIDATE	; 0a
	const LIGHTNING_ROD	; 0b
	const SAND_RUSH		; 0c
	const HUSTLE		; 0d
	const CUTE_CHARM	; 0e
	const FLASH_FIRE	; 0f
	const DROUGHT		; 10
	const INNER_FOCUS	; 11
	const STENCH		; 12
	const EFFECT_SPORE	; 13
	const SAND_FORCE	; 14
	const PICKUP		; 15
	const LIMBER		; 16
	const CLOUD_NINE	; 17
	const DEFIANT		; 18
	const SWIFT_SWIM	; 19
	const SYNCHRONIZE	; 1a
	const GUTS			; 1b
	const LIQUID_OOZE	; 1c
	const STURDY		; 1d
	const FLAME_BODY	; 1e
	const OWN_TEMPO		; 1f
	const EARLY_BIRD	; 20
	const THICK_FAT		; 21
	const SHELL_ARMOR	; 22
	const LEVITATE		; 23
	const INSOMNIA		; 24
	const STATIC		; 25
	const HARVEST		; 26
	const ROCK_HEAD		; 27
	const NATURAL_CURE	; 28
	const REGENERATOR	; 29
	const TECHNICIAN	; 2a
	const MOXIE			; 2b
	const HYDRATION		; 2c
	const IMPOSTER		; 2d
	const WATER_ABSORB	; 2e
	const VOLT_ABSORB	; 2f
	const TRACE			; 30
	const WEAK_ARMOR	; 31
	const PRESSURE		; 32
	const MULTISCALE	; 33
	const LEAF_GUARD	; 34
	const SHEER_FORCE	; 35
	const SUPER_LUCK	; 36
	const HUGE_POWER	; 37
	const DRIZZLE		; 38
	const SPEED_BOOST	; 39
	const SHADOW_TAG	; 3a
	const SAP_SIPPER	; 3b
	const IMMUNITY		; 3c
	const POISON_POINT	; 3d
	const MOODY			; 3e
	const SAND_STREAM	; 3f
NUM_ABILITIES EQU const_value