; MoveEffectsPointers indexes (see data/moves/effects_pointers.asm)

	const_def
	const EFFECT_NORMAL_HIT
	const EFFECT_SLEEP
	const EFFECT_POISON_HIT
	const EFFECT_LEECH_HIT
	const EFFECT_BURN_HIT
	const EFFECT_FREEZE_HIT
	const EFFECT_PARALYZE_HIT
	const EFFECT_SELFDESTRUCT
	const EFFECT_DREAM_EATER
	const EFFECT_ATTACK_DOWN
	const EFFECT_DEFENSE_DOWN
	const EFFECT_SPEED_DOWN
	const EFFECT_SP_ATK_DOWN
	const EFFECT_SP_DEF_DOWN
	const EFFECT_ACCURACY_DOWN
	const EFFECT_EVASION_DOWN
	const EFFECT_BIDE
	const EFFECT_RAMPAGE
	const EFFECT_FORCE_SWITCH
	const EFFECT_MULTI_HIT
	const EFFECT_FLINCH_HIT
	const EFFECT_TOXIC
	const EFFECT_PAY_DAY
	const EFFECT_TRI_ATTACK
	const EFFECT_STRUGGLE
	const EFFECT_OHKO
	const EFFECT_RAZOR_WIND
	const EFFECT_SUPER_FANG
	const EFFECT_STATIC_DAMAGE
	const EFFECT_TRAP_TARGET
	const EFFECT_UNUSED_2B
	const EFFECT_DOUBLE_HIT
	const EFFECT_JUMP_KICK
	const EFFECT_RECOIL_HIT
	const EFFECT_CONFUSE
	const EFFECT_ATTACK_DOWN_2
	const EFFECT_DEFENSE_DOWN_2
	const EFFECT_SPEED_DOWN_2
	const EFFECT_SP_ATK_DOWN_2
	const EFFECT_SP_DEF_DOWN_2
	const EFFECT_ACCURACY_DOWN_2
	const EFFECT_EVASION_DOWN_2
	const EFFECT_POISON
	const EFFECT_PARALYZE
	const EFFECT_ATTACK_DOWN_HIT
	const EFFECT_DEFENSE_DOWN_HIT
	const EFFECT_SPEED_DOWN_HIT
	const EFFECT_SP_ATK_DOWN_HIT
	const EFFECT_SP_DEF_DOWN_HIT
	const EFFECT_ACCURACY_DOWN_HIT
	const EFFECT_EVASION_DOWN_HIT
	const EFFECT_SKY_ATTACK
	const EFFECT_CONFUSE_HIT
	const EFFECT_POISON_MULTI_HIT
	const EFFECT_UNUSED_4E
	const EFFECT_HYPER_BEAM
	const EFFECT_RAGE
	const EFFECT_MIMIC
	const EFFECT_LEECH_SEED
	const EFFECT_DISABLE
	const EFFECT_LEVEL_DAMAGE
	const EFFECT_PSYWAVE
	const EFFECT_COUNTER
	const EFFECT_ENCORE
	const EFFECT_PAIN_SPLIT
	const EFFECT_SNORE
	const EFFECT_LOCK_ON
	const EFFECT_DEFROST_OPPONENT
	const EFFECT_REVERSAL
	const EFFECT_SPITE
	const EFFECT_FALSE_SWIPE
	const EFFECT_PRIORITY_HIT
	const EFFECT_TRIPLE_KICK
	const EFFECT_THIEF
	const EFFECT_NIGHTMARE
	const EFFECT_FLAME_WHEEL
	const EFFECT_FORESIGHT
	const EFFECT_ROLLOUT
	const EFFECT_SWAGGER
	const EFFECT_FURY_CUTTER
	const EFFECT_ATTRACT
	const EFFECT_RETURN
	const EFFECT_PRESENT
	const EFFECT_FRUSTRATION
	const EFFECT_SACRED_FIRE
	const EFFECT_MAGNITUDE
	const EFFECT_PURSUIT
	const EFFECT_RAPID_SPIN
	const EFFECT_UNUSED_82
	const EFFECT_UNUSED_83
	const EFFECT_HIDDEN_POWER
	const EFFECT_DEFENSE_UP_HIT
	const EFFECT_ATTACK_UP_HIT
	const EFFECT_ALL_UP_HIT
	const EFFECT_FAKE_OUT
	const EFFECT_MIRROR_COAT
	const EFFECT_SKULL_BASH
	const EFFECT_TWISTER
	const EFFECT_EARTHQUAKE
	const EFFECT_FUTURE_SIGHT
	const EFFECT_GUST
	const EFFECT_STOMP
	const EFFECT_SOLARBEAM
	const EFFECT_THUNDER
	const EFFECT_BEAT_UP
	const EFFECT_FLY
	const EFFECT_BLIZZARD
	const EFFECT_BODY_SLAM
	const EFFECT_ALWAYS_HIT ; 3
	const EFFECT_MIRROR_MOVE ; 1
	const EFFECT_ATTACK_UP ; 2
	const EFFECT_DEFENSE_UP ; 2
	const EFFECT_SPEED_UP ; 0
	const EFFECT_SP_ATK_UP ; 1
	const EFFECT_SP_DEF_UP ; 0
	const EFFECT_ACCURACY_UP ; 0
	const EFFECT_EVASION_UP ; 1
	const EFFECT_RESET_STATS ; 1
	const EFFECT_CONVERSION ; 1
	const EFFECT_HEAL ; 4
	const EFFECT_LIGHT_SCREEN ; 1
	const EFFECT_MIST ; 1
	const EFFECT_FOCUS_ENERGY ; 1
	const EFFECT_ATTACK_UP_2 ; 1
	const EFFECT_DEFENSE_UP_2 ; 2
	const EFFECT_SPEED_UP_2 ; 1
	const EFFECT_SP_ATK_UP_2 ; 0
	const EFFECT_SP_DEF_UP_2 ; 1
	const EFFECT_ACCURACY_UP_2 ; 0
	const EFFECT_EVASION_UP_2 ; 1
	const EFFECT_TRANSFORM ; 1
	const EFFECT_REFLECT ; 1
	const EFFECT_SUBSTITUTE ; 1
	const EFFECT_METRONOME ; 1
	const EFFECT_SPLASH ; 1
	const EFFECT_CONVERSION2 ; 1
	const EFFECT_SKETCH ; 1
	const EFFECT_SLEEP_TALK ; 1
	const EFFECT_DESTINY_BOND ; 1
	const EFFECT_HEAL_BELL ; 1
	const EFFECT_MEAN_LOOK ; 2
	const EFFECT_CURSE ; 1
	const EFFECT_UNUSED_6E
	const EFFECT_PROTECT ; 2
	const EFFECT_SPIKES ; 1
	const EFFECT_PERISH_SONG ; 1
	const EFFECT_SANDSTORM ; 1
	const EFFECT_ENDURE ; 1
	const EFFECT_SAFEGUARD ; 1
	const EFFECT_BATON_PASS ; 1
	const EFFECT_MORNING_SUN ; 1
	const EFFECT_SYNTHESIS ; 1
	const EFFECT_MOONLIGHT ; 1
	const EFFECT_RAIN_DANCE ; 1
	const EFFECT_SUNNY_DAY ; 1
	const EFFECT_BELLY_DRUM ; 1
	const EFFECT_PSYCH_UP ; 1
	const EFFECT_TELEPORT ; 1
	const EFFECT_DEFENSE_CURL ; 1
	const EFFECT_HAIL ; 1
NUM_MOVE_EFECTS EQU const_value
