; See data/maps/scenes.asm for which maps have scene variables.
; Each scene_script and coord_event is associated with a current scene ID.

; Scene variables default to 0.
SCENE_DEFAULT  EQU 0
; Often a map will have a one-time default event for scene 0, and switch to a
; do-nothing scene 1 when the event finishes.
SCENE_FINISHED EQU 1
; A coord_event for scene -1 will always activate, regardless of the map's
; scene variable value.
SCENE_ALWAYS   EQU -1

; wPokecenter2FSceneID
	const_def 1
	const SCENE_POKECENTER2F_LEAVE_TRADE_CENTER       ; 1
	const SCENE_POKECENTER2F_LEAVE_COLOSSEUM          ; 2
	const SCENE_POKECENTER2F_LEAVE_MOBILE_TRADE_ROOM  ; 3
	const SCENE_POKECENTER2F_LEAVE_MOBILE_BATTLE_ROOM ; 4

; wPowerPlantSceneID
	const_def
	const SCENE_POWERPLANT_NOTHING               ; 0
	const SCENE_POWERPLANT_GUARD_GETS_PHONE_CALL ; 1

; wCeruleanGymSceneID
	const_def
	const SCENE_CERULEANGYM_NOTHING        ; 0
	const SCENE_CERULEANGYM_GRUNT_RUNS_OUT ; 1

; wRoute25SceneID
	const_def
	const SCENE_ROUTE25_NOTHING     ; 0
	const SCENE_ROUTE25_MISTYS_DATE ; 1

; wElmsLabSceneID
	const_def 1
	const SCENE_ELMSLAB_CANT_LEAVE            ; 1
	const SCENE_ELMSLAB_NOTHING               ; 2
	const SCENE_ELMSLAB_MEET_OFFICER          ; 3
	const SCENE_ELMSLAB_READ_BOOKSHELVES      ; 4
	const SCENE_ELMSLAB_AIDE_GIVES_POKE_BALLS ; 5

; wRoute35NationalParkGateSceneID
	const_def
	const SCENE_ROUTE35NATIONALPARKGATE_NOTHING             ; 0
	const SCENE_ROUTE35NATIONALPARKGATE_UNUSED              ; 1
	const SCENE_ROUTE35NATIONALPARKGATE_LEAVE_CONTEST_EARLY ; 2

; wRoute36SceneID
	const_def
	const SCENE_ROUTE36_NOTHING ; 0
	const SCENE_ROUTE36_SUICUNE ; 1

; wRoute36NationalParkGateSceneID
	const_def
	const SCENE_ROUTE36NATIONALPARKGATE_NOTHING             ; 0
	const SCENE_ROUTE36NATIONALPARKGATE_UNUSED              ; 1
	const SCENE_ROUTE36NATIONALPARKGATE_LEAVE_CONTEST_EARLY ; 2

; wAzaleaTownSceneID
	const_def
	const SCENE_AZALEATOWN_NOTHING              ; 0
	const SCENE_AZALEATOWN_RIVAL_BATTLE         ; 1
	const SCENE_AZALEATOWN_KURT_RETURNS_GS_BALL ; 2

; wRoute42SceneID
	const_def
	const SCENE_ROUTE42_NOTHING ; 0
	const SCENE_ROUTE42_SUICUNE ; 1

; wCianwoodCitySceneID
	const_def
	const SCENE_CIANWOODCITY_NOTHING            ; 0
	const SCENE_CIANWOODCITY_SUICUNE_AND_EUSINE ; 1

; wBurnedTower1FSceneID
	const_def 1
	const SCENE_BURNEDTOWER1F_RIVAL_BATTLE ; 1
	const SCENE_BURNEDTOWER1F_NOTHING      ; 2

; wRuinsOfAlphOutsideSceneID
	const_def
	const SCENE_RUINSOFALPHOUTSIDE_NOTHING       ; 0
	const SCENE_RUINSOFALPHOUTSIDE_GET_UNOWN_DEX ; 1

; wRuinsOfAlphResearchCenterSceneID
	const_def
	const SCENE_RUINSOFALPHRESEARCHCENTER_NOTHING       ; 0
	const SCENE_RUINSOFALPHRESEARCHCENTER_GET_UNOWN_DEX ; 1

; wRuinsOfAlphInnerChamberSceneID
	const_def
	const SCENE_RUINSOFALPHINNERCHAMBER_NOTHING          ; 0
	const SCENE_RUINSOFALPHINNERCHAMBER_STRANGE_PRESENCE ; 1

; wMahoganyMart1FSceneID
	const_def
	const SCENE_MAHOGANYMART1F_NOTHING               ; 0
	const SCENE_MAHOGANYMART1F_LANCE_UNCOVERS_STAIRS ; 1

; wTeamRocketBaseB2FSceneID
	const_def 1
	const SCENE_TEAMROCKETBASEB2F_ROCKET_BOSS ; 1
	const SCENE_TEAMROCKETBASEB2F_ELECTRODES  ; 2
	const SCENE_TEAMROCKETBASEB2F_NOTHING     ; 3

; wTeamRocketBaseB3FSceneID
	const_def 1
	const SCENE_TEAMROCKETBASEB3F_RIVAL_ENCOUNTER ; 1
	const SCENE_TEAMROCKETBASEB3F_ROCKET_BOSS     ; 2
	const SCENE_TEAMROCKETBASEB3F_NOTHING         ; 3

; wDragonsDenB1FSceneID
	const_def
	const SCENE_DRAGONSDENB1F_NOTHING        ; 0
	const SCENE_DRAGONSDENB1F_CLAIR_GIVES_TM ; 1

; wOlivinePortSceneID
	const_def 1
	const SCENE_OLIVINEPORT_LEAVE_SHIP ; 1

; wVermilionPortSceneID
	const_def 1
	const SCENE_VERMILIONPORT_LEAVE_SHIP ; 1

; wFastShip1FSceneID
	const_def 1
	const SCENE_FASTSHIP1F_ENTER_SHIP   ; 1
	const SCENE_FASTSHIP1F_MEET_GRANDPA ; 2

; wGoldenrodHospitalReception
	const_def
	const SCENE_GOLDENROD_HOSPITAL_DEFAULT 			  ; 0
	const SCENE_GOLDENROD_HOSPITAL_NEED_TO_WASH_HANDS ; 1

; wGoldenrodHospitalCorridorsAndRoomsSceneID
	const_def
	const SCENE_GOLDENROD_HOSPITAL_NO_SEARCH			; 0
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_1
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_2
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_3
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_4
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_5
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_6
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_7
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_8
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_9
	const SCENE_GOLDENROD_HOSPITAL_NURSE_SEARCH_STEP_10

; wVaccinationCenter1F
	const_def 1
	const SCENE_VACCINATION_CENTER_FIND_SEAT	; 1
	const SCENE_VACCINATION_CENTER_YOUR_TURN	; 2

; wVaccinationCenterCorridor
	const_def
	const SCENE_VACCINATION_CENTER_CORRIDOR_GO_TO_ROOM	; 0
	const SCENE_VACCINATION_CENTER_CORRIDOR_GO_TO_LOBBY	; 1
