	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, WATER, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, BROWN, BROWN, RED, RED, GRAY, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, RED
