	tilepal 0, GRAY, BROWN, WATER, WATER, RED, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, RED, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, GREEN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, BROWN, BROWN
	tilepal 0, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GREEN, WATER, BROWN, BROWN
	tilepal 0, BROWN, GREEN, BROWN, BROWN, WATER, WATER, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, YELLOW
	tilepal 1, WATER, WATER, GRAY, GRAY, WATER, RED, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW
	tilepal 1, WATER, BROWN, GRAY, GRAY, GREEN, GREEN, YELLOW, WATER
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, RED, GRAY, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, GRAY, YELLOW, GRAY, GRAY, GRAY, WATER
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, GRAY, GREEN
	tilepal 1, BROWN, BROWN, WATER, YELLOW, GRAY, GRAY, GRAY, WATER
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
