	tilepal 0, WATER, GRAY, GRAY, GRAY, RED, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, BROWN, BROWN, BROWN
	tilepal 0, BROWN, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, BROWN, BROWN, WATER
	tilepal 0, WATER, BROWN, BROWN, BROWN, WATER, ROOF, WATER, WATER
	tilepal 0, WATER, WATER, BROWN, BROWN, GRAY, BROWN, BROWN, ROOF
	tilepal 0, WATER, GRAY, WATER, BROWN, WATER, ROOF, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, WATER, WATER, WATER, BROWN, GRAY, BROWN, BROWN, GRAY
	tilepal 1, GRAY, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 1, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 1, GRAY, TEXT
