SECTION "Sprites 1", ROMX

ChrisSpriteGFX::               INCBIN "gfx/sprites/chris.2bpp"
ChrisBikeSpriteGFX::           INCBIN "gfx/sprites/chris_bike.2bpp"
GameboyKidSpriteGFX::          INCBIN "gfx/sprites/gameboy_kid.2bpp"
SilverSpriteGFX::              INCBIN "gfx/sprites/silver.2bpp"
OakSpriteGFX::                 INCBIN "gfx/sprites/oak.2bpp"
RedSpriteGFX::                 INCBIN "gfx/sprites/red.2bpp"
BlueSpriteGFX::                INCBIN "gfx/sprites/blue.2bpp"
BillSpriteGFX::                INCBIN "gfx/sprites/bill.2bpp"
ElderSpriteGFX::               INCBIN "gfx/sprites/elder.2bpp"
JanineSpriteGFX::              INCBIN "gfx/sprites/janine.2bpp"
KurtSpriteGFX::                INCBIN "gfx/sprites/kurt.2bpp"
MomSpriteGFX::                 INCBIN "gfx/sprites/mom.2bpp"
BlaineSpriteGFX::              INCBIN "gfx/sprites/blaine.2bpp"
RedsMomSpriteGFX::             INCBIN "gfx/sprites/reds_mom.2bpp"
DaisySpriteGFX::               INCBIN "gfx/sprites/daisy.2bpp"
ElmSpriteGFX::                 INCBIN "gfx/sprites/elm.2bpp"
WillSpriteGFX::                INCBIN "gfx/sprites/will.2bpp"
FalknerSpriteGFX::             INCBIN "gfx/sprites/falkner.2bpp"
WhitneySpriteGFX::             INCBIN "gfx/sprites/whitney.2bpp"
BugsySpriteGFX::               INCBIN "gfx/sprites/bugsy.2bpp"
MortySpriteGFX::               INCBIN "gfx/sprites/morty.2bpp"
ChuckSpriteGFX::               INCBIN "gfx/sprites/chuck.2bpp"
JasmineSpriteGFX::             INCBIN "gfx/sprites/jasmine.2bpp"
PryceSpriteGFX::               INCBIN "gfx/sprites/pryce.2bpp"
ClairSpriteGFX::               INCBIN "gfx/sprites/clair.2bpp"
BrockSpriteGFX::               INCBIN "gfx/sprites/brock.2bpp"
KarenSpriteGFX::               INCBIN "gfx/sprites/karen.2bpp"
BrunoSpriteGFX::               INCBIN "gfx/sprites/bruno.2bpp"
MistySpriteGFX::               INCBIN "gfx/sprites/misty.2bpp"
LanceSpriteGFX::               INCBIN "gfx/sprites/lance.2bpp"
SurgeSpriteGFX::               INCBIN "gfx/sprites/surge.2bpp"
ErikaSpriteGFX::               INCBIN "gfx/sprites/erika.2bpp"
KogaSpriteGFX::                INCBIN "gfx/sprites/koga.2bpp"
SabrinaSpriteGFX::             INCBIN "gfx/sprites/sabrina.2bpp"
CooltrainerMSpriteGFX::        INCBIN "gfx/sprites/cooltrainer_m.2bpp"
CooltrainerFSpriteGFX::        INCBIN "gfx/sprites/cooltrainer_f.2bpp"
BugCatcherSpriteGFX::          INCBIN "gfx/sprites/bug_catcher.2bpp"
TwinSpriteGFX::                INCBIN "gfx/sprites/twin.2bpp"
YoungsterSpriteGFX::           INCBIN "gfx/sprites/youngster.2bpp"
LassSpriteGFX::                INCBIN "gfx/sprites/lass.2bpp"
TeacherSpriteGFX::             INCBIN "gfx/sprites/teacher.2bpp"
BeautySpriteGFX::              INCBIN "gfx/sprites/beauty.2bpp"
SuperNerdSpriteGFX::           INCBIN "gfx/sprites/super_nerd.2bpp"
RockerSpriteGFX::              INCBIN "gfx/sprites/rocker.2bpp"
    
    
SECTION "Sprites 2", ROMX

PokefanMSpriteGFX::            INCBIN "gfx/sprites/pokefan_m.2bpp"
PokefanFSpriteGFX::            INCBIN "gfx/sprites/pokefan_f.2bpp"
GrampsSpriteGFX::              INCBIN "gfx/sprites/gramps.2bpp"
GrannySpriteGFX::              INCBIN "gfx/sprites/granny.2bpp"
SwimmerGuySpriteGFX::          INCBIN "gfx/sprites/swimmer_guy.2bpp"
SwimmerGirlSpriteGFX::         INCBIN "gfx/sprites/swimmer_girl.2bpp"
BigSnorlaxSpriteGFX::          INCBIN "gfx/sprites/big_snorlax.2bpp"
SurfingPikachuSpriteGFX::      INCBIN "gfx/sprites/surfing_pikachu.2bpp"
RocketSpriteGFX::              INCBIN "gfx/sprites/rocket.2bpp"
RocketGirlSpriteGFX::          INCBIN "gfx/sprites/rocket_girl.2bpp"
NurseSpriteGFX::               INCBIN "gfx/sprites/nurse.2bpp"
LinkReceptionistSpriteGFX::    INCBIN "gfx/sprites/link_receptionist.2bpp"
ClerkSpriteGFX::               INCBIN "gfx/sprites/clerk.2bpp"
FisherSpriteGFX::              INCBIN "gfx/sprites/fisher.2bpp"
FishingGuruSpriteGFX::         INCBIN "gfx/sprites/fishing_guru.2bpp"
ScientistSpriteGFX::           INCBIN "gfx/sprites/scientist.2bpp"
KimonoGirlSpriteGFX::          INCBIN "gfx/sprites/kimono_girl.2bpp"
SageSpriteGFX::                INCBIN "gfx/sprites/sage.2bpp"
UnusedGuySpriteGFX::           INCBIN "gfx/sprites/unused_guy.2bpp"
GentlemanSpriteGFX::           INCBIN "gfx/sprites/gentleman.2bpp"
BlackBeltSpriteGFX::           INCBIN "gfx/sprites/black_belt.2bpp"
ReceptionistSpriteGFX::        INCBIN "gfx/sprites/receptionist.2bpp"
OfficerSpriteGFX::             INCBIN "gfx/sprites/officer.2bpp"
JennySpriteGFX::               INCBIN "gfx/sprites/jenny.2bpp"
AgathaSpriteGFX::              INCBIN "gfx/sprites/agatha.2bpp"
CalSpriteGFX::                 INCBIN "gfx/sprites/cal.2bpp"
SlowpokeSpriteGFX::            INCBIN "gfx/sprites/slowpoke.2bpp"
CaptainSpriteGFX::             INCBIN "gfx/sprites/captain.2bpp"
BigLaprasSpriteGFX::           INCBIN "gfx/sprites/big_lapras.2bpp"
GymGuideSpriteGFX::            INCBIN "gfx/sprites/gym_guide.2bpp"
SailorSpriteGFX::              INCBIN "gfx/sprites/sailor.2bpp"
BikerSpriteGFX::               INCBIN "gfx/sprites/biker.2bpp"
PharmacistSpriteGFX::          INCBIN "gfx/sprites/pharmacist.2bpp"
MonsterSpriteGFX::             INCBIN "gfx/sprites/monster.2bpp"
FairySpriteGFX::               INCBIN "gfx/sprites/fairy.2bpp"
BirdSpriteGFX::                INCBIN "gfx/sprites/bird.2bpp"
DragonSpriteGFX::              INCBIN "gfx/sprites/dragon.2bpp"
BigOnixSpriteGFX::             INCBIN "gfx/sprites/big_onix.2bpp"
N64SpriteGFX::                 INCBIN "gfx/sprites/n64.2bpp"
SudowoodoSpriteGFX::           INCBIN "gfx/sprites/sudowoodo.2bpp"
SurfSpriteGFX::                INCBIN "gfx/sprites/surf.2bpp"
PokeBallSpriteGFX::            INCBIN "gfx/sprites/poke_ball.2bpp"
PokedexSpriteGFX::             INCBIN "gfx/sprites/pokedex.2bpp"
PaperSpriteGFX::               INCBIN "gfx/sprites/paper.2bpp"
VirtualBoySpriteGFX::          INCBIN "gfx/sprites/virtual_boy.2bpp"
InvisibleWallSpriteGFX::	   INCBIN "gfx/sprites/invisible_wall.2bpp"
RockSpriteGFX::                INCBIN "gfx/sprites/rock.2bpp"
BoulderSpriteGFX::             INCBIN "gfx/sprites/boulder.2bpp"
SnesSpriteGFX::                INCBIN "gfx/sprites/snes.2bpp"
FamicomSpriteGFX::             INCBIN "gfx/sprites/famicom.2bpp"
FruitTreeSpriteGFX::           INCBIN "gfx/sprites/fruit_tree.2bpp"
GoldTrophySpriteGFX::          INCBIN "gfx/sprites/gold_trophy.2bpp"
SilverTrophySpriteGFX::        INCBIN "gfx/sprites/silver_trophy.2bpp"
KrisSpriteGFX::                INCBIN "gfx/sprites/kris.2bpp"
KrisBikeSpriteGFX::            INCBIN "gfx/sprites/kris_bike.2bpp"
SuicuneSpriteGFX::             INCBIN "gfx/sprites/suicune.2bpp"
EnteiSpriteGFX::               INCBIN "gfx/sprites/entei.2bpp"
RaikouSpriteGFX::              INCBIN "gfx/sprites/raikou.2bpp"

SECTION "Sprites 3", ROMX
ShineSpriteGFX::	           INCBIN "gfx/sprites/shine.2bpp"
ConeSpriteGFX::                INCBIN "gfx/sprites/cone.2bpp"
SubstituteSpriteGFX::          INCBIN "gfx/sprites/substitute.2bpp"
SquirtleSquadSpriteGFX::       INCBIN "gfx/sprites/cool_squirtle.2bpp"
OldAmberSpriteGFX::            INCBIN "gfx/sprites/old_amber.2bpp"
MewtwoOwTopSpriteGFX::         INCBIN "gfx/sprites/mewtwo_ow_top.2bpp"
MewtwoOwBottomSpriteGFX::      INCBIN "gfx/sprites/mewtwo_ow_bottom.2bpp"
LoreleiSpriteGFX::             INCBIN "gfx/sprites/lorelei.2bpp"
WalkingPikachuSpriteGFX::      INCBIN "gfx/sprites/pikachu.2bpp"
CooltrainerMSpriteGFX_Clap::   INCBIN "gfx/sprites/cooltrainer_m_clap.2bpp"
SuperNerdSpriteGFX_Clap::      INCBIN "gfx/sprites/super_nerd_clap.2bpp"
ReceptionistSpriteGFX_Clap::   INCBIN "gfx/sprites/receptionist_clap.2bpp"
FisherSpriteGFX_Clap::          INCBIN "gfx/sprites/fisher_clap.2bpp"
    
SECTION "Sprites 4", ROMX
ChrisClapSpriteGFX::           INCBIN "gfx/sprites/chris_clap.2bpp" ; Must stay in the same bank as KrisClapSpriteGFX.
KrisClapSpriteGFX::            INCBIN "gfx/sprites/kris_clap.2bpp"  ; Must stay in the same bank as ChrisClapSpriteGFX.